# Put code in automations.yaml

- alias: "Switch coffeemaker off"
  initial_state: 'on'
  hide_entity: true
  trigger:
    platform: state
    entity_id: switch.YOUR_SWITCH
    to: 'on'
    for:
      minutes: 30

    
  action:
    service: notify.ios_YOUR_IPHONE
    data:
      title: "Coffeemaker is on!"
      message: "It has been on for 30 minutes."
      data:
        push:
          badge: 0
          category: "coffeemaker"
        action_data:
          entity_id: switch.YOUR_SWITCH

            
            
- alias: "IOS push Coffeemaker"
  initial_state: 'on'
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: COFFEEMAKEROFF
  action:
    - service: switch.turn_off
      entity_id: switch.YOUR_SWITCH
      
    - service: notify.ios_YOUR_IPHONE
      data:
        message: "Coffeemaker is switched off"
    
        
